# Generated by Django 2.1.2 on 2018-10-29 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_auto_20181029_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='fic',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
