# Generated by Django 2.2.28 on 2022-11-18 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_auto_20181230_0313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('post_id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('posted_date', models.DateTimeField()),
                ('word_count', models.PositiveIntegerField()),
                ('chapters', models.PositiveIntegerField(default=1)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='forum.Member')),
                ('fic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='forum.Fic')),
            ],
        ),
    ]
