# Generated by Django 2.2.28 on 2022-12-22 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0012_auto_20221119_0132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('post_id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('threadmark_title', models.CharField(max_length=255)),
                ('posted_date', models.DateTimeField()),
                ('word_count', models.PositiveIntegerField()),
                ('fic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='forum.Fic')),
            ],
            options={
                'ordering': ('fic', 'posted_date'),
            },
        ),
    ]
