# Generated by Django 2.2.28 on 2022-08-04 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forum', '0010_auto_20181230_0313'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlitzReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.BooleanField(default=False)),
                ('score', models.PositiveIntegerField()),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('post_id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('posted_date', models.DateTimeField()),
                ('word_count', models.PositiveIntegerField()),
                ('chapters', models.PositiveIntegerField(default=1)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='forum.Member')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewBlitzScoring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('min_words', models.PositiveIntegerField()),
                ('words_per_chapter', models.PositiveIntegerField()),
                ('chapter_points', models.DecimalField(decimal_places=2, max_digits=3)),
                ('consecutive_chapter_interval', models.PositiveIntegerField()),
                ('consecutive_chapter_bonus', models.DecimalField(decimal_places=2, max_digits=3)),
                ('theme_bonus', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewBlitz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('reviews', models.ManyToManyField(through='reviewblitz.BlitzReview', to='reviewblitz.Review')),
                ('scoring', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blitzes', to='reviewblitz.ReviewBlitzScoring')),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='blitzes',
            field=models.ManyToManyField(through='reviewblitz.BlitzReview', to='reviewblitz.ReviewBlitz'),
        ),
        migrations.AddField(
            model_name='review',
            name='fic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='forum.Fic'),
        ),
        migrations.AddField(
            model_name='blitzreview',
            name='blitz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blitz_reviews', to='reviewblitz.ReviewBlitz'),
        ),
        migrations.AddField(
            model_name='blitzreview',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blitz_reviews', to='reviewblitz.Review'),
        ),
    ]
