# Generated by Django 2.2.28 on 2022-11-16 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewblitz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blitzreview',
            options={'permissions': (('approve', 'Can approve or reject reviews'),)},
        ),
        migrations.AlterModelOptions(
            name='reviewblitz',
            options={'verbose_name_plural': 'Review blitzes'},
        ),
    ]
