# Generated by Django 2.2.28 on 2022-11-18 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviewblitz', '0002_auto_20221116_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blitzreview',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blitz_reviews', to='forum.Review'),
        ),
        migrations.AlterField(
            model_name='reviewblitz',
            name='reviews',
            field=models.ManyToManyField(through='reviewblitz.BlitzReview', to='forum.Review'),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
