# Generated by Django 2.2.28 on 2022-12-22 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0013_chapter'),
        ('reviewblitz', '0005_auto_20221222_0213'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlitzUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus_points', models.DecimalField(decimal_places=2, max_digits=4)),
                ('points_spent', models.DecimalField(decimal_places=2, max_digits=4)),
                ('blitz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blitzes', to='reviewblitz.ReviewBlitz')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blitz_members', to='forum.Member')),
            ],
        ),
    ]
