# Generated by Django 2.2.28 on 2022-12-22 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewblitz', '0006_blitzuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blitzuser',
            name='bonus_points',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='blitzuser',
            name='points_spent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
