# Generated by Django 5.0 on 2023-12-20 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewblitz', '0008_weeklytheme_alter_blitzreview_id_alter_blitzuser_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewblitztheme',
            options={'ordering': ['week']},
        ),
        migrations.AlterField(
            model_name='reviewblitztheme',
            name='blitz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_themes', to='reviewblitz.reviewblitz'),
        ),
        migrations.AlterField(
            model_name='weeklytheme',
            name='claimable',
            field=models.CharField(choices=[('per_chapter', 'Per chapter'), ('per_review', 'Per review'), ('per_fic', 'Per fic')], default='per_fic', max_length=11),
        ),
    ]
