# Generated by Django 5.0 on 2023-12-25 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewblitz', '0009_alter_reviewblitztheme_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklytheme',
            name='subsequent_chapter_theme_bonus',
            field=models.BooleanField(default=False, help_text="Check this box to automatically apply the theme bonus to all chapters after the first in multi-chapter reviews (only relevant if the theme is claimable per chapter). This would be appropriate if the theme is something like 'Any chapterfic' or 'Any story you've already reviewed before'. If not checked for a per-chapter theme, the theme bonus will be applied for all the chapters if the box is checked or no chapters otherwise."),
        ),
        migrations.AlterField(
            model_name='weeklytheme',
            name='claimable',
            field=models.CharField(choices=[('per_chapter', 'Per chapter'), ('per_review', 'Per review'), ('per_fic', 'Per fic')], default='per_fic', help_text='Per chapter means the bonus can be claimed once per chapter covered by a review. Per review means it can be claimed only once per review, though it could be claimed multiple times per fic in separate reviews. Per fic means it can be claimed once per fic for this week.', max_length=11),
        ),
    ]
