# Generated by Django 5.1.4 on 2024-12-19 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewblitz', '0011_reviewblitzscoring_max_ratio_bonus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blitzreview',
            name='heat_bonus',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
    ]
