# Generated by Django 5.1.4 on 2024-12-19 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewblitz', '0012_blitzreview_heat_bonus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewblitzscoring',
            name='max_ratio_bonus',
        ),
        migrations.RemoveField(
            model_name='reviewblitzscoring',
            name='ratio_bonus_multiplier',
        ),
        migrations.AddField(
            model_name='reviewblitzscoring',
            name='heat_bonus_multiplier',
            field=models.DecimalField(decimal_places=2, default=0, help_text='The multiplier applied to the ratio of (reviews given + 1) / (reviews received + 1) to determine the heat bonus. (Set to 0 to disable this bonus.)', max_digits=3),
        ),
        migrations.AddField(
            model_name='reviewblitzscoring',
            name='max_heat_bonus',
            field=models.DecimalField(decimal_places=2, default=0, help_text='The maximum heat bonus that can be given.', max_digits=3),
        ),
    ]
