# Generated by Django 5.1.4 on 2024-12-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewblitz', '0013_remove_reviewblitzscoring_max_ratio_bonus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewblitzscoring',
            name='heat_bonus_threshold_tier_1',
            field=models.PositiveIntegerField(default=5, help_text='The number of effective chapters reviewed required to reach the tier 1 maximum heat bonus.'),
        ),
        migrations.AddField(
            model_name='reviewblitzscoring',
            name='heat_bonus_threshold_tier_2',
            field=models.PositiveIntegerField(default=20, help_text='The number of effective chapters reviewed required to reach the full maximum heat bonus.'),
        ),
        migrations.AddField(
            model_name='reviewblitzscoring',
            name='max_heat_bonus_tier_0',
            field=models.DecimalField(decimal_places=2, default=0, help_text='The maximum heat bonus that can be given below the tier 1 threshold.', max_digits=3),
        ),
        migrations.AddField(
            model_name='reviewblitzscoring',
            name='max_heat_bonus_tier_1',
            field=models.DecimalField(decimal_places=3, default=0, help_text='The maximum heat bonus that can be given below the tier 2 threshold.', max_digits=3),
        ),
        migrations.AlterField(
            model_name='reviewblitzscoring',
            name='max_heat_bonus',
            field=models.DecimalField(decimal_places=2, default=0, help_text='The maximum heat bonus that can be given, after reaching the tier 2 threshold.', max_digits=3),
        ),
    ]
