# Generated by Django 5.1.4 on 2024-12-22 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewblitz', '0014_reviewblitzscoring_heat_bonus_threshold_tier_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewblitzscoring',
            name='max_heat_bonus_tier_1',
            field=models.DecimalField(decimal_places=2, default=0, help_text='The maximum heat bonus that can be given below the tier 2 threshold.', max_digits=3),
        ),
    ]
