# Generated by Django 2.1.2 on 2018-12-30 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serebii', '0009_fic_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='fic',
            name='related_fics',
            field=models.ManyToManyField(blank=True, related_name='_fic_related_fics_+', to='serebii.Fic'),
        ),
        migrations.AddField(
            model_name='genre',
            name='slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fic',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='fics', to='serebii.Genre'),
        ),
        migrations.AlterField(
            model_name='fictag',
            name='fic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='serebii.Fic'),
        ),
    ]
