# Generated by Django 2.1.2 on 2018-10-29 00:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0013_auto_20180111_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficeligibility',
            name='year',
            field=models.PositiveIntegerField(db_index=True, default=2018, validators=[django.core.validators.MinValueValidator(2008), django.core.validators.MaxValueValidator(2018)]),
        ),
        migrations.AlterField(
            model_name='nomination',
            name='year',
            field=models.PositiveIntegerField(db_index=True, default=2018, validators=[django.core.validators.MinValueValidator(2008), django.core.validators.MaxValueValidator(2018)]),
        ),
        migrations.AlterField(
            model_name='vote',
            name='year',
            field=models.PositiveIntegerField(db_index=True, default=2018, validators=[django.core.validators.MinValueValidator(2008), django.core.validators.MaxValueValidator(2018)]),
        ),
        migrations.AlterField(
            model_name='yearaward',
            name='year',
            field=models.PositiveIntegerField(db_index=True, default=2018, validators=[django.core.validators.MinValueValidator(2008), django.core.validators.MaxValueValidator(2018)]),
        ),
    ]
