# Generated by Django 2.2.28 on 2022-08-04 17:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0014_auto_20181029_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficeligibility',
            name='year',
            field=models.PositiveIntegerField(db_index=True, default=2022, validators=[django.core.validators.MinValueValidator(2008), django.core.validators.MaxValueValidator(2022)]),
        ),
        migrations.AlterField(
            model_name='nomination',
            name='year',
            field=models.PositiveIntegerField(db_index=True, default=2022, validators=[django.core.validators.MinValueValidator(2008), django.core.validators.MaxValueValidator(2022)]),
        ),
        migrations.AlterField(
            model_name='vote',
            name='year',
            field=models.PositiveIntegerField(db_index=True, default=2022, validators=[django.core.validators.MinValueValidator(2008), django.core.validators.MaxValueValidator(2022)]),
        ),
        migrations.AlterField(
            model_name='yearaward',
            name='year',
            field=models.PositiveIntegerField(db_index=True, default=2022, validators=[django.core.validators.MinValueValidator(2008), django.core.validators.MaxValueValidator(2022)]),
        ),
    ]
